### ISSUE TITLE
Make it so the redemptions do not get auto accepted

### ISSUE THREAD

**Issue by VulpesHD** [Nerixyz/rewards#107]
I would like to see each redemption in the reward request queue in the twitch dashboard, so if something happens, I could refund the users, but the bot currently accepts everything right away.

**Comment by Nerixyz** [comment]
Is this how you imagine it:

```mermaid
stateDiagram
  state "Add to queue" as add
  [*] --> Unfulfilled
  Unfulfilled --> Execute
  Execute --> Canceled: Error
  Execute --> add: Success
  add --> Fulfilled: Accepted
  add --> Canceled: Rejected
```

...this should be simple. However, I've heard requests of having the following in mind:

```mermaid
stateDiagram
  state "Add to queue" as add
  [*] --> Unfulfilled
  Unfulfilled --> add
  add --> Execute: Accepted
  add --> Canceled: Rejected
```

I'm not sure if the bot can update the status of the redemption after it has been accepted.

**Comment by VulpesHD** [comment]
Both are fine
What I was thinking of is:
Someone redeems a channel points reward, lets say, add a 7TV emote:
They click on redeem reward under the twitch chat => Emote gets added => But the bot does not click on accept inside the reward queue, the redemption stays there in the dashboard for me to decide what I want to do with their channel points.

This "issue" came up, when I added the "queue a track on Spotify" reward, because so many people redeemed it, the queue got very long, but the stream ended early and I wanted to refund the points to people, whose songs did not get played, but I saw nothing in the twitch dashboard.
